spring:
  application:
    name: url-shortener-backend
  profiles:
    active: dev


server:
  port: ${PORT:8080}

jwt:
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

