spring:
  application:
    name: url-shortener-backend
  datasource:
    url:  jdbc:mysql://localhost:3306/url_shortener_db
    username: root
    password: Alok303017

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharsLong123
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    com.college.urlshortener: INFO