spring:
  application:
    name: url-shortener-backend
  datasource:
    url:  jdbc:mysql://localhost:3306/url_shortener_db
    username: root
    password: Alok303017

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms  # fail fast if Redis is down


jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharsLong123
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    com.college.urlshortener: INFO

app:
  anonymous:
    daily-limit: 3
    alias-limit: 1
  authenticated:
    daily-limit: 20
    alias-limit: 5